DEV-1296 gradle oss compatibility
gatling/frontline-gradle-plugin pull request #1
Opened 2020-08-25 13:42 UTC by Isammoc

See https://gatlingcorp.atlassian.net/browse/DEV-1296 to get a sample test.

2020-08-31 13:29 UTC, slandelle requested changes

2020-08-31 13:29 UTC, slandelle commented on README.md
> +It creates a fat jar without gatling dependencies (that will be provided by FrontLine itself).
It creates a package in the format expected by [Gatling FrontLine](https://gatling.io/gatling-frontline/).

What you're explaining are implementation details.

2020-08-31 18:04 UTC, Isammoc commented on README.md
> +It creates a fat jar without gatling dependencies (that will be provided by FrontLine itself).
done

2020-08-31 19:12 UTC, slandelle requested changes

2020-08-31 19:12 UTC, slandelle commented on src/main/groovy/io/gatling/frontline/gradle/FrontLinePlugin.groovy
> +            println("io.gatling.gradle not found, applying it")
println => project.logger.debug

2020-08-31 19:12 UTC, slandelle commented on src/main/groovy/io/gatling/frontline/gradle/FrontLineShadowJar.groovy
> +        Set<String> result = new HashSet<String>()
Sad to allocate that many intermediate HashSets. Why not instantiate the accumulator once like I did?

2020-08-31 19:12 UTC, slandelle commented on src/main/groovy/io/gatling/frontline/gradle/FrontLineShadowJar.groovy
> +        result += id.group + ":" + id.name
I think it would be cleaner to introduce a dedicated record type that implements equals and hashcode than using String. In particular, this forces use to make sure you build those String the same way in `wantedFiles` below.

2020-09-01 08:00 UTC, tpetillot commented on src/main/groovy/io/gatling/frontline/gradle/FrontLineShadowJar.groovy
> +        Set<String> gd = myCollectGatlingDepsRec(getResolvedConfiguration().getFirstLevelModuleDependencies())
```suggestion
        Set<String> gatlingDeps = myCollectGatlingDepsRec(getResolvedConfiguration().getFirstLevelModuleDependencies())
```

2020-09-01 09:24 UTC, Isammoc commented on src/main/groovy/io/gatling/frontline/gradle/FrontLinePlugin.groovy
> +            println("io.gatling.gradle not found, applying it")
done

2020-09-01 09:24 UTC, Isammoc commented on src/main/groovy/io/gatling/frontline/gradle/FrontLineShadowJar.groovy
> +        Set<String> result = new HashSet<String>()
done

2020-09-01 09:24 UTC, Isammoc commented on src/main/groovy/io/gatling/frontline/gradle/FrontLineShadowJar.groovy
> +        result += id.group + ":" + id.name
done, but not convinced

2020-09-01 09:24 UTC, Isammoc commented on src/main/groovy/io/gatling/frontline/gradle/FrontLineShadowJar.groovy
> +        Set<String> gd = myCollectGatlingDepsRec(getResolvedConfiguration().getFirstLevelModuleDependencies())
done

2020-09-03 08:41 UTC, tpetillot approved these changes

2020-09-03 16:56 UTC, slandelle requested changes

2020-09-03 16:56 UTC, slandelle commented on build.gradle
> +  runtime "gradle.plugin.io.gatling.gradle:gatling-gradle-plugin:3.3.4-SNAPSHOT"
Should we use the beta3 we've just released and use it here for now?

2020-09-04 08:58 UTC, Isammoc commented on build.gradle
> +  runtime "gradle.plugin.io.gatling.gradle:gatling-gradle-plugin:3.3.4-SNAPSHOT"
:+1:

2020-09-10 16:57 UTC, slandelle requested changes

2020-09-10 16:57 UTC, slandelle commented on README.md
> +# FrontLine Gradle plugin
We don't want a full README. Usage is purely for FrontLine customer and that's what the README should advertise. Full documentation must go in the FrontLine User Guide.

2020-09-10 16:57 UTC, slandelle commented on build.gradle
> +    url "https://plugins.gradle.org/m2/"
What is this for?

2020-09-10 17:01 UTC, Isammoc commented on build.gradle
> +    url "https://plugins.gradle.org/m2/"
to be able to add the gatling-gradle-plugin runtime dependency

2020-09-10 17:09 UTC, Isammoc commented on README.md
> +# FrontLine Gradle plugin
README changed to a lighter version.

Only to let the information for future dev

2020-09-11 11:42 UTC, slandelle approved these changes

2020-09-11 12:01 UTC, merged